spring.application.name=utn

spring.datasource.url=jdbc:postgresql://dpg-d9fn3hrrjlhs73am49d0-a.oregon-postgres.render.com:5432/smartwasteutn
spring.datasource.username=smartwasteutn_user
spring.datasource.password=fLxImWY7NcHpYdPiGoSMRrCp4sTx2LBe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bastidaspaul83@gmail.com
spring.mail.password=dzwl chwq wzoc loau
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=*
app.contenedor.umbral.critico=80
app.contenedor.umbral.medio=40